project:
  type: website
  output-dir: docs

website:
  title: "P566 Lab 12"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html: 
    theme: minty
    css: styles.css
    toc: true
    